### PR TITLE
Wrote some tests for the youtube download method.

### PR DESCRIPTION
**Pull request by ehgoodenough**
I put the tests in the same spec suite as ffmpeg, since I wanted to run those two specs with each other. Now you don't have to worry about setting up anything for those tests!
- Wrote more tests for youtube downloading.
- Hid the tests that touch external sources.
- Attempted to fix travis again.

### CODE REVIEW

**Comment by ehgoodenough** [comment]
@tzorca: The tests can take _forever_ to run, but I'd love if you'd download them and make sure they work. Thanks! Stay warm, and take some time off.

**Comment by tmjz402** [comment]
Is Travis really working correctly now? That's great!

**Comment by ehgoodenough** [comment]
I know right? I only "fixed" it by removing frisby tests, since those were the ones that were unable to reach the server. So at the moment, we're only running unit tests; no smoke tests.

**Comment by tmjz402** [comment]
Finished in 190.926 seconds
3 tests, 7 assertions, 0 failures, 0 skipped

Slow, but at least they all passed. I had to extend the timeouts, though.

**Pull request merged**
